apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t8c5dt2xo-nodejs 
  janus-idp.io/tekton: t8c5dt2xo-nodejs
  backstage.io/kubernetes-id: t8c5dt2xo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t8c5dt2xo-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml