apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t8c5dt2xo-nodejs
  janus-idp.io/tekton: t8c5dt2xo-nodejs
  backstage.io/kubernetes-id: t8c5dt2xo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t8c5dt2xo-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
