apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: t8c5dt2xo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t8c5dt2xo-nodejs 
  name: t8c5dt2xo-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: t8c5dt2xo-nodejs
    weight: 100 
